#!/usr/bin/env bash
dry_run="0"

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
echo $script_dir

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi


if [ -z "$script_dir" ]; then
    echo "env var $script_dir needs to be present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $script_dir"

update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf $directory
            fi

            log "    copying env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                cp -r ./$c $2
            fi
        done

    )
    popd &> /dev/null
}

copy() {
    log "removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

update_files $script_dir/env/.config $XDG_CONFIG_HOME
update_files $script_dir/env/.local $HOME/.local

copy $script_dir/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
copy $script_dir/env/.zsh_profile $HOME/.zsh_profile
copy $script_dir/env/.zshrc $HOME/.zshrc
copy $script_dir/env/.xprofile $HOME/.xprofile
copy $script_dir/env/.tmux-sessionizer $HOME/.tmux-sessionizer
copy $script_dir/dev-env $HOME/.local/scripts/dev-env
copy $script_dir/tmux-dev-prod $HOME/.local/bin/tmux-dev-prod-course-ready

