- hosts: localhost
  tasks:
    - name: Include main vars
      ansible.builtin.include_vars:
        file: vars.yml

    - name: Copy dev env
      ansible.builtin.copy:
        src: ./env/
        dest: "{{ home }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'



