- name: New SSH Keys for Ansible
  hosts: localhost
  vars:
    ssh_key_filename: 
  tasks:
    - name: "Create .ssh"
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: '0755'

    - name: generate SSH key "id_rsa"
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no

