#!/usr/bin/env bash

sudo apt -y install cmake gettext lua5.1 liblua5.1-0-dev
sudo rm -f $(which nvim)

# DANGEROUS
rm -rf $HOME/personal/harpoon
rm -rf $HOME/personal/vim-apm
rm -rf $HOME/personal/vim-with-me
rm -rf $HOME/personal/vim-arcade
rm -rf $HOME/personal/plenary


